version: "3.9"
services:
  app:
    build: .
    image: "kubera:latest"
    container_name: "kubera"
    env_file:
      - .env
    ports:
      - "4567:4567"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - kubera

  postgres:
    image: postgres:14-alpine
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kubera

networks:
  kubera:
