version: "3.9"
services:
  app:
    build: .
    image: "kubera"
    container_name: "kubera"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: admin
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      APP_SECRET_KEY: dev
      FLASK_DEBUG: true
    ports:
      - "4567:4567"
    networks:
      - kubera

  postgres:
    image: postgres:14-alpine
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin
    networks:
      - kubera

  grafana:
    build:
      dockerfile: ./grafana/Dockerfile
      context: ./
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - kubera

networks:
  kubera:
