apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crashloop
  template:
    metadata:
      labels:
        app: crashloop
    spec:
      containers:
        - name: crashloop-container
          image: busybox:1.36.1
          # This container forcibly exits with nonzero status (after sleeping 3s)
          # => CrashLoopBackOff
          command: ["sh", "-c", "echo 'Crashing...'; sleep 3; exit 1"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oomtest
  template:
    metadata:
      labels:
        app: oomtest
    spec:
      containers:
        - name: oom-container
          image: busybox:1.36.1
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "64Mi"
          # This script tries to allocate more memory than the limit => OOMKilled
          command:
            [
              "sh",
              "-c",
              "echo 'Allocating a lot of memory...' && base64 /dev/urandom | head -c 200000000 > /dev/null",
            ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: errimagepull-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: errimagepull
  template:
    metadata:
      labels:
        app: errimagepull
    spec:
      containers:
        - name: impossible-image-container
          # Non-existent image => ErrImagePull / ImagePullBackOff
          image: some-nonexistent-repo/impossible-image:404
          command: ["sh", "-c", "echo 'This image does not exist' && sleep 300"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: failing-liveness-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: failing-liveness
  template:
    metadata:
      labels:
        app: failing-liveness
    spec:
      containers:
        - name: failing-liveness-container
          image: busybox:1.36.1
          command:
            ["sh", "-c", "echo 'Running but never healthy...' && sleep 100000"]
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          # The container never listens on port 80 => liveness checks fail => CrashLoop
