apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubera.fullname" . }}
  labels: {{- include "kubera.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 4567
      name: https
  selector: {{- include "kubera.selectorLabels" . | nindent 4 }}
