name: Destroy EKS Stack

on:
  workflow_dispatch: # Manual trigger

jobs:
  destroy-eks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Change directory
        run: cd terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Destroy)
        run: terraform plan -destroy -out=destroyplan.tfplan

      - name: Terraform Destroy
        run: terraform apply -auto-approve destroyplan.tfplan
